const avatarParts={
 hairStyles:["hair1","hair2","hair3","hair4","hair5","hair6","hair7","hair8"],
 hairColors:["#6b3f2a","#2e241e","#d6a32a","#7e4d9d","#365c8d","#b34d58","#2d6b50"],
 skins:["#f0d29a","#e5b98a","#c99670","#8d634e"],
 clothingPalettes:[
   ["#2d4c9b","#e2d7ad","#7c3442"],
   ["#8d3543","#e7c661","#4f315e"],
   ["#3f7b58","#d9e4b0","#6a4b2e"],
   ["#704798","#e0c6ef","#2f405b"],
   ["#bf7429","#f2d58c","#5b3f27"],
   ["#345c83","#69a8bd","#e4e5df"],
   ["#6f3c3c","#b98655","#2c2f39"]
 ],
 boots:["#49382e","#2f2f35","#6d492c","#263c45"],
 faces:["• •","˘ ˘","• ᴗ","^ ^","• ω","- -"],
 items:["⚔","✦","♣","◆","☂","★","☘","⌁"]
};
let avatar={hairStyle:"hair1",hair:"#6b3f2a",skin:"#f0d29a",clothes:["#2d4c9b","#e2d7ad","#7c3442"],boots:"#49382e",face:"• •",item:"⚔"};
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function randomizeAvatar(){avatar={hairStyle:pick(avatarParts.hairStyles),hair:pick(avatarParts.hairColors),skin:pick(avatarParts.skins),clothes:pick(avatarParts.clothingPalettes),boots:pick(avatarParts.boots),face:pick(avatarParts.faces),item:pick(avatarParts.items)};renderAvatarPreview();}
function renderAvatarPreview(){const hair=document.getElementById("avHair");hair.className="avHair "+avatar.hairStyle;const preview=document.getElementById("avatarPreview");preview.style.setProperty("--hair",avatar.hair);preview.style.setProperty("--skin",avatar.skin);preview.style.setProperty("--clothes1",avatar.clothes[0]);preview.style.setProperty("--clothes2",avatar.clothes[1]);preview.style.setProperty("--clothes3",avatar.clothes[2]);preview.style.setProperty("--boots",avatar.boots);preview.style.setProperty("--face",'"'+avatar.face+'"');document.getElementById("avItem").textContent=avatar.item;document.getElementById("avatarMeta").textContent="髪型・顔・3色の服・持ち物がランダムで変わります。何度でも作り直せます。";}
function applyAvatarToGame(){const root=document.documentElement;root.style.setProperty("--avatar-hair",avatar.hair);root.style.setProperty("--avatar-skin",avatar.skin);root.style.setProperty("--avatar-clothes1",avatar.clothes[0]);root.style.setProperty("--avatar-clothes2",avatar.clothes[1]);root.style.setProperty("--avatar-clothes3",avatar.clothes[2]);root.style.setProperty("--avatar-boots",avatar.boots);}
function confirmAvatar(){applyAvatarToGame();document.getElementById("avatarScreen").classList.add("hidden");document.getElementById("game").classList.remove("hidden");render();}
let mode="village";let px=7,py=7,currentSite=null;let talked={traveler:false,researcher:false,elder:false};let activeNpc=null,dialogIndex=0,afterDialog=null;
const villageRows=["FFFFFFFFFFFFFF","F....H....H..F","F............F","F...PPPPPP...F","F...P....P...F","GPPPPPPPPP...F","F...P....P...F","F...PPPPPP...F","F............F","F....H.......F","FFFFFFFFFFFFFF"];
const npcs={"5,4":{id:"traveler",name:"旅人",cls:"",lines:["旅に出るなら、まず世界遺産のことを少し知っておくといいよ。","世界遺産には「文化遺産」「自然遺産」「複合遺産」の3つの種類があるんだ。"]},"9,4":{id:"researcher",name:"森の研究者",cls:"researcher",lines:["自然遺産は、すばらしい自然や、生き物、地形などに大きな価値がある場所だよ。","これから日本の自然遺産をめぐるなら、どんな自然が守られているのか見てみると面白いよ。"]},"7,6":{id:"elder",name:"村の長老",cls:"elder",lines:["世界遺産として認められるための「登録基準」は、全部で10個ある。","今は10個の中身まで覚えなくてよいぞ。旅をしながら少しずつ知っていけばよい。"]}};
const guard={id:"guard",name:"門番",cls:"guard",before:["この先は日本の自然遺産へ続く道だ。","まだ準備が整っていないようだな。村の3人に話を聞いてくるといい。"],after:["3人から話を聞いてきたようだな。","準備ができたようだ。門を開けよう。","日本の自然遺産をめぐる旅へ、いってらっしゃい！"]};
const japanRows=["~~~~~~~~~~~~~~~~~~~~~~~~~~","~~~~~~~~~~~~~~~~~~~LLL~~~~","~~~~~~~~~~~~~~~~~~LLLLL~~~","~~~~~~~~~~~~~~~~~~LLLLSLL~","~~~~~~~~~~~~~~~~~~~LLLL~~~","~~~~~~~~~~~~~~~~~~~~LL~~~~~","~~~~~~~~~~~~~~~~~~~~w~~~~~","~~~~~~~~~~~~~~~~~~~LLL~~~~","~~~~~~~~~~~~~~~~~~LSLL~~~~","~~~~~~~~~~~~~~~~~LLLL~~~~~","~~~~~~~~~~~~L~~~LLLL~~~~~~","~~~~~~~~~~~~L~LLLLL~~~~~~~","~~~~~~~~~~~~LLLLLL~~~~~~~~","~~~~~~~~~~LLLLLLLLwwwwwww~","~~~~~~wwLLLLLL~~~~~~~~~w~~","~~~~~LLwLLLw~~~~~~~~~~~w~~","~~~~LLLL~~LLLL~~~~~~~~~w~~","~~~~LLL~~~~LL~~~~~~~~~~w~~","~~~~LL~~~~~~~~~~~~~~~~~L~~","~~~~~S~~~~~~~~~~~~~~~~~S~~","~~~www~~~~~~~~~~~~~~~~~~~~","~~~wL~~~~~~~~~~~~~~~~~~~~~","~wLL~~~~~~~~~~~~~~~~~~~~~~","~S~~~~~~~~~~~~~~~~~~~~~~~~"];
const sites={"22,3":"知床","19,8":"白神山地","5,19":"屋久島","1,23":"奄美大島、徳之島、沖縄島北部及び西表島","23,19":"小笠原諸島"};
const regionLabels={"20,2":"北海道","16,12":"本州","12,10":"佐渡島","12,16":"四国","5,17":"九州","2,22":"沖縄諸島","24,19":"小笠原"};
const lockedSites={"19,4":"北海道・北東北の縄文遺跡群","18,9":"平泉―仏国土（浄土）を表す建築・庭園及び考古学的遺跡群","17,11":"日光の社寺","16,12":"富岡製糸場と絹産業遺産群","16,13":"ル・コルビュジエの建築作品―近代建築運動への顕著な貢献","14,13":"富士山―信仰の対象と芸術の源泉","12,13":"白川郷・五箇山の合掌造り集落","12,10":"佐渡島の金山","10,14":"古都京都の文化財（京都市、宇治市、大津市）","11,14":"古都奈良の文化財","10,15":"法隆寺地域の仏教建造物","9,15":"飛鳥・藤原の宮都","11,16":"紀伊山地の霊場と参詣道","10,16":"百舌鳥・古市古墳群―古代日本の墳墓群","8,15":"姫路城","9,14":"石見銀山遺跡とその文化的景観","8,14":"広島平和記念碑（原爆ドーム）","6,15":"「神宿る島」宗像・沖ノ島と関連遺産群","5,16":"明治日本の産業革命遺産 製鉄・製鋼、造船、石炭産業","4,17":"長崎と天草地方の潜伏キリシタン関連遺産","3,22":"琉球王国のグスク及び関連遺産群","7,16":"厳島神社"};
const QUESTION_DATA_SOURCES=["./data/sekaken_4_2024_03_rpg.json","https://raw.githubusercontent.com/tetsushi-ikeno/world-heritage-quest/main/data/sekaken_4_2024_03_rpg.json"];
let questionBank=[];let questionBankReady=false;let questionBankError="";let currentQuestion=null;
async function loadQuestionBank(){questionBankReady=false;questionBankError="";let lastError=null;for(const url of QUESTION_DATA_SOURCES){try{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error("HTTP "+response.status);const data=await response.json();if(!data||!Array.isArray(data.問題))throw new Error("問題配列がありません");questionBank=data.問題.filter(q=>q.採用===true);questionBankReady=true;updateDifficultyButtons();return;}catch(err){lastError=err;}}questionBank=[];questionBankReady=false;questionBankError=lastError?String(lastError.message||lastError):"読み込みに失敗しました";updateDifficultyButtons();}
function questionsFor(siteName,level){return questionBank.filter(q=>q.採用===true&&q.遺産名===siteName&&Number(q.難易度)===Number(level));}
function updateDifficultyButtons(){const status=document.getElementById("questionBankStatus");if(!status)return;status.classList.remove("error");if(!questionBankReady){if(questionBankError){status.textContent="過去問題データを読み込めませんでした。";status.classList.add("error");}else{status.textContent="過去問題データを読み込み中...";}for(let level=1;level<=3;level++){const btn=document.getElementById("levelBtn"+level);const info=document.getElementById("levelInfo"+level);if(btn)btn.disabled=true;if(info)info.textContent=questionBankError?"利用できません":"確認中...";}return;}status.textContent="2024年3月実施の公式過去問題データから出題します。";for(let level=1;level<=3;level++){const pool=questionsFor(currentSite,level);const btn=document.getElementById("levelBtn"+level);const info=document.getElementById("levelInfo"+level);if(!btn||!info)continue;btn.disabled=pool.length===0;info.textContent=pool.length>0?"正解 +"+level+"pt　問題 "+pool.length+"問":"問題なし";}}
let points={"知床":0,"白神山地":0,"小笠原諸島":0,"屋久島":0,"奄美大島、徳之島、沖縄島北部及び西表島":0};let discovered={"知床":false,"白神山地":false,"小笠原諸島":false,"屋久島":false,"奄美大島、徳之島、沖縄島北部及び西表島":false};let currentLevel=1;let transitionLock=false;
function starsFor(siteName){const p=points[siteName]||0;if(p>=20)return 3;if(p>=10)return 2;if(p>=1)return 1;return 0;}function isMaster(siteName){return starsFor(siteName)===3}function starText(siteName){const n=starsFor(siteName);return "★".repeat(n)+"☆".repeat(3-n);}
function setGuideMessage(text){const el=document.getElementById("guideMessage");if(el)el.textContent=text;}function setMapTitle(text){const el=document.getElementById("mapTitle");if(el)el.textContent=text;}function allTalked(){return talked.traveler&&talked.researcher&&talked.elder}function rows(){return mode==="village"?villageRows:japanRows}
function recommendedSiteKey(){if(mode!=="japan")return null;let bestKey=null,bestDistance=Infinity;for(const [key,siteName] of Object.entries(sites)){if(discovered[siteName])continue;const [x,y]=key.split(",").map(Number);const distance=Math.abs(x-px)+Math.abs(y-py);if(distance<bestDistance){bestDistance=distance;bestKey=key;}}return bestKey;}
function updateMapScale(){const wrap=document.getElementById("mapWrap");const r=rows();if(!wrap||!r.length||wrap.clientWidth===0||wrap.clientHeight===0)return;const W=r[0].length,H=r.length;const availableW=Math.max(0,wrap.clientWidth-18);const availableH=Math.max(0,wrap.clientHeight-18);const fit=Math.floor(Math.min(availableW/W,availableH/H));const cap=mode==="village"?60:40;const tile=Math.max(22,Math.min(cap,fit));document.documentElement.style.setProperty("--tile",tile+"px");}
function render(){const r=rows(),W=r[0].length,H=r.length;const map=document.getElementById("map");const recommended=recommendedSiteKey();map.innerHTML="";map.dataset.mode=mode;map.style.gridTemplateColumns=`repeat(${W},var(--tile))`;map.style.gridTemplateRows=`repeat(${H},var(--tile))`;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const d=document.createElement("div"),c=r[y][x],key=x+","+y;let cls="";if(mode==="village"){cls=c==="F"?"forest":c==="P"?"path":c==="H"?"house":c==="G"?"gate":"grass";if(npcs[key]){const n=npcs[key];cls+=" npc "+n.cls+" "+(talked[n.id]?"done":"need");}if(key==="1,5")cls+=" guard"+(allTalked()?" need":"");}else{if(lockedSites[key]){cls="lockedSite";}else if(c==="~"){cls="sea";}else if(c==="w"){cls="sailable";}else if(c==="S"){const siteName=sites[key];if(siteName&&isMaster(siteName)){cls="site master";}else if(siteName&&points[siteName]>0){cls="site cleared";}else if(siteName&&discovered[siteName]){cls="site discovered";}else{cls="site undiscovered"+(key===recommended?" recommended":"");}}else{cls="land";}}d.className="tile "+cls+(x===px&&y===py?" player":"");d.dataset.x=x;d.dataset.y=y;if(x===px&&y===py){const av=document.createElement("div");av.className="mapAvatar";av.innerHTML='<div class="mapHair"></div><div class="mapFace"></div><div class="mapBody"></div><div class="mapItem">'+avatar.item+'</div>';d.appendChild(av);}if(mode==="japan"&&regionLabels[key]){const label=document.createElement("span");label.className="regionLabel";label.textContent=regionLabels[key];d.appendChild(label);}map.appendChild(d);}const hud=document.getElementById("progressHud");if(mode==="japan"){hud.classList.add("show");const total=Object.values(points).reduce((a,b)=>a+b,0);const cleared=Object.values(points).filter(v=>v>0).length;document.getElementById("totalPoints").textContent=total+" pt";document.getElementById("clearCount").textContent=cleared+" / "+Object.keys(points).length;const totalStars=Object.keys(points).reduce((sum,n)=>sum+starsFor(n),0);const masters=Object.keys(points).filter(isMaster).length;document.getElementById("starCount").textContent=totalStars+" / "+(Object.keys(points).length*3);document.getElementById("masterCount").textContent=masters+" / "+Object.keys(points).length;}else{hud.classList.remove("show");}if(mode==="village"){setMapTitle("はじまりの村");setGuideMessage(allTalked()?"3人から話を聞けたね！ 左にいる門番に話しかけて、旅に出よう！":"「！」がついている3人に話しかけて、世界遺産のことを教えてもらおう！");document.getElementById("status").textContent="ピラミトンが冒険を案内してくれます。";document.getElementById("legend").textContent="！＝まだ話していない　✓＝会話済み";}else{setMapTitle("日本の自然遺産");setGuideMessage("「？」はまだ見つけていない世界遺産だよ。明るく目立つ「？」を目印に歩いてみよう！");document.getElementById("status").textContent="水色の海は渡れるよ。濃い青の海には進めないよ。";document.getElementById("legend").textContent="？＝未発見　！＝発見済み　✓＝クリア　★＝MASTER　🔒＝？？？";}requestAnimationFrame(updateMapScale);}
function isNpc(x,y){return npcs[x+","+y]}function isGuard(x,y){return x===1&&y===5}function passable(x,y){const r=rows(),c=r[y][x];if(mode==="village"){if(c==="F"||c==="H"||c==="G")return false;if(isNpc(x,y)||isGuard(x,y))return false;return true;}return c!=="~";}
function move(dx,dy){if(transitionLock)return;const r=rows(),W=r[0].length,H=r.length;const nx=px+dx,ny=py+dy;if(nx<0||ny<0||nx>=W||ny>=H)return;const npc=isNpc(nx,ny);if(mode==="village"&&npc){startNpcDialog(npc);return;}if(mode==="village"&&isGuard(nx,ny)){startGuardDialog();return;}if(!passable(nx,ny)){setGuideMessage(mode==="village"?"そこには進めないみたいだよ。":"そこは渡れない海だよ。水色の海を探してみよう！");return;}px=nx;py=ny;render();if(mode==="japan"&&lockedSites[px+","+py]){setGuideMessage("🔒 ここはまだ「？？？」だよ。日本の自然遺産をすべてクリアすると発見できるようになるみたい！");return;}if(mode==="japan"&&sites[px+","+py]){currentSite=sites[px+","+py];if(!discovered[currentSite]){discoverCurrentSite();}else{openSiteDialog();}}}
function handleMapTap(event){const tile=event.target.closest(".tile");if(!tile||!document.getElementById("map").contains(tile))return;const tx=Number(tile.dataset.x),ty=Number(tile.dataset.y);const dx=tx-px,dy=ty-py;if(Math.abs(dx)+Math.abs(dy)!==1)return;move(dx,dy);}
function handleKeyboardMove(event){if(document.getElementById("game").classList.contains("hidden"))return;const key=event.key.toLowerCase();const directions={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]};const direction=directions[key];if(!direction)return;event.preventDefault();move(direction[0],direction[1]);}
function openSiteDialog(){document.getElementById("siteName").textContent=currentSite;document.getElementById("siteStatus").textContent=isMaster(currentSite)?"★ MASTER　"+starText(currentSite):points[currentSite]>0?"✓ クリア済み　"+starText(currentSite):"！ 発見済み・未クリア　"+starText(currentSite);document.getElementById("sitePoints").textContent="この遺産のポイント： "+points[currentSite]+" pt　（★2:10pt / MASTER:20pt）";updateDifficultyButtons();document.getElementById("game").classList.add("hidden");document.getElementById("siteDialog").classList.remove("hidden");}
function discoverCurrentSite(){transitionLock=true;const overlay=document.getElementById("encounterOverlay");overlay.classList.remove("run");overlay.style.removeProperty("opacity");overlay.style.removeProperty("transform");overlay.style.animation="none";void overlay.offsetWidth;overlay.style.removeProperty("animation");void overlay.offsetWidth;overlay.classList.add("run");setTimeout(()=>{discovered[currentSite]=true;document.getElementById("game").classList.add("hidden");document.getElementById("discoveryName").textContent=currentSite;document.getElementById("discovery").classList.remove("hidden");},650);setTimeout(()=>{overlay.classList.remove("run");overlay.style.removeProperty("opacity");overlay.style.removeProperty("transform");transitionLock=false;},850);}
function continueFromDiscovery(){document.getElementById("discovery").classList.add("hidden");openSiteDialog();}
function openDialog(npc,callback=null){activeNpc=npc;dialogIndex=0;afterDialog=callback;document.getElementById("game").classList.add("hidden");document.getElementById("dialog").classList.remove("hidden");showDialogLine();}
function startNpcDialog(npc){openDialog(npc,()=>{talked[npc.id]=true;render();});}
function startGuardDialog(){if(!allTalked()){openDialog({id:"guard",name:"門番",lines:guard.before});}else{openDialog({id:"guard",name:"門番",lines:guard.after},()=>{enterJapanMap();});}}
function showDialogLine(){document.getElementById("speaker").textContent=activeNpc.name;document.getElementById("dialogText").textContent=activeNpc.lines[dialogIndex];}
function nextDialog(){dialogIndex++;if(dialogIndex<activeNpc.lines.length){showDialogLine();return;}document.getElementById("dialog").classList.add("hidden");document.getElementById("game").classList.remove("hidden");const cb=afterDialog;afterDialog=null;if(cb)cb();else render();}
function enterJapanMap(){mode="japan";px=14;py=12;render();setGuideMessage("日本の自然遺産をめぐる旅のスタート！ まずは「？」を探してみよう！");}
function startQuiz(level){const pool=questionsFor(currentSite,level);if(!questionBankReady||pool.length===0){updateDifficultyButtons();return;}currentLevel=level;currentQuestion=pool[Math.floor(Math.random()*pool.length)];document.getElementById("siteDialog").classList.add("hidden");document.getElementById("quiz").classList.remove("hidden");document.getElementById("quizSite").textContent=currentSite+"：難易度"+level;document.getElementById("question").textContent=currentQuestion.問題文;const rate=currentQuestion.正答率!=null?" ｜ 正答率："+currentQuestion.正答率+"%":"";const original=currentQuestion.元問題番号!=null?" ｜ 元問題：問"+currentQuestion.元問題番号:"";document.getElementById("questionSource").textContent="出典："+currentQuestion.出典+rate+original;document.getElementById("feedback").textContent="";document.getElementById("quizBack").classList.add("hidden");const answers=document.getElementById("answers");answers.innerHTML="";currentQuestion.選択肢.forEach((label,index)=>{const b=document.createElement("button");b.className="answer";b.textContent=label;b.onclick=()=>answer(index);answers.appendChild(b);});}
function answer(selectedIndex){document.querySelectorAll(".answer").forEach(b=>b.disabled=true);if(!currentQuestion)return;const ok=(selectedIndex+1===Number(currentQuestion.正解));if(ok){const gain=currentLevel;const beforeStars=starsFor(currentSite);points[currentSite]+=gain;const afterStars=starsFor(currentSite);let eventText="";if(beforeStars===0&&afterStars>=1)eventText="　✓ クリア！ ★を獲得！";if(beforeStars<2&&afterStars>=2)eventText="　★★にランクアップ！";if(beforeStars<3&&afterStars>=3)eventText="　★★★ MASTER！ 「"+currentSite+"マスター」";document.getElementById("feedback").textContent="セカイ博士：おみごと！ 正解じゃ！ +"+gain+"pt　この遺産： "+points[currentSite]+"pt　"+starText(currentSite)+eventText;}else{const correctIndex=Number(currentQuestion.正解)-1;const correct=currentQuestion.選択肢[correctIndex]||"正解";document.getElementById("feedback").textContent="セカイ博士：おしい！ 正解は「"+correct+"」じゃ。";}document.getElementById("quizBack").classList.remove("hidden");}
function backToMap(){document.getElementById("discovery").classList.add("hidden");document.getElementById("siteDialog").classList.add("hidden");document.getElementById("quiz").classList.add("hidden");document.getElementById("game").classList.remove("hidden");render();}
document.getElementById("map").addEventListener("click",handleMapTap);
document.addEventListener("keydown",handleKeyboardMove);
window.addEventListener("resize",()=>requestAnimationFrame(updateMapScale));
loadQuestionBank();randomizeAvatar();render();
